version: '3.8'
services:
  flask_app:
    build:
      context: .
    container_name: flask_shopping_landing
    ports:
      - "5001:5000"
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
