version: '3.8'

services:
  app:
    container_name: shopping_landing_app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    networks:
      - tienda_network
    restart: always
networks:
  tienda_network:
    driver: bridge

volumes:
  logs:
